### ISSUE TITLE
Include meta tags for sending blog post to social media

### ISSUE THREAD

**Issue by trf000** [AppStateESS/stories#1]
Currently only needed by Facebook, but I bet Twitter comes along with something similar.

<meta property="og:url" content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<meta property="og:type" content="article" />
<meta property="og:title" content="When Great Minds Don’t Think Alike" />
<meta property="og:description"  content="How much does culture influence creative thinking?" />
<meta property="og:image" content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />

**Comment by Stardog** [comment]
We'll add this.
https://developers.facebook.com/docs/sharing/webmasters

**Comment by Stardog** [comment]
Going to make separate code to handle this. Will ease incorporation into older modules as well.
