### ISSUE TITLE
Separate thumbnail image for summary

### ISSUE THREAD

**Issue by trf000** [AppStateESS/stories#4]
Designated image for summary and meta tags. Have a flag to display on full post. Have a flag in settings to require/not require thumbnail image. (some may not need/want it for every post.)

**Comment by Stardog** [comment]
Entries will have a thumbnail and summary variable. These will be used for feature windows. There will be a checkbox for this just like the old "show previous" list on the front page.
Outside of this, there should be a fragment post with a read more button or a complete post. I figure for the fragment, the read more will show the complete post with an anchor to push the reader to the unread portion.
Does there need to be a flag to require the thumbnail or can we just not make it required? The responsibility would then lie with the administrator.
https://developers.facebook.com/docs/sharing/webmasters

**Comment by Stardog** [comment]
This is done-ish. Meta tags will be handled in different module.
